# Generated by Django 5.1.4 on 2025-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
