# Generated by Django 5.1.4 on 2025-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_alter_curso_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
