# Generated by Django 5.1.4 on 2025-01-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0003_alter_curso_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
