# Generated by Django 5.1.4 on 2025-01-11 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_customuser_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
