# Generated by Django 5.1.4 on 2025-01-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_customuser_date_joined"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="nome",
            new_name="username",
        ),
    ]
